sudo: required
services:
  - docker

before_install:
  - docker build -t markozjovanovic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true markozjovanovic/docker-react npm run test



deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-410349628157"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY